apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: default
spec:
  containers:
    - image: python-liveness:1.0 
      name: test
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      env:
      - name: PORT
        value: "8080"
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 15
        failureThreshold: 1
      resources:
        limits:
          cpu: "200m"
          memory: "100Mi"
        requests:
          cpu: "100m"